spring.application.name=elastic-beanstalk-lab

# Port 5000 is what Elastic Beanstalk expects by default
server.port=5000

# These are overridden by EB environment variables in production
APP_VERSION=1.0.0
DYNAMO_ENABLED=false
DYNAMO_TABLE=AppVisits
DYNAMO_REGION=us-west-1